exclude: ^bazel-
repos:
  - repo: https://github.com/warchant/pre-commit-buildifier
    rev: 0.1.3
    hooks:
      - id: buildifier
        args: ["--version=v8.0.3", "--lint=warn", "--warnings=all", "-v"]
