@startuml

participant User
participant "iox::log" as logFreeFunction << free function >>
participant Logger << static functions >>
participant "logger : DefaultLogger" as defaultLoggerInstance

User -> logFreeFunction ++ : initLogger

logFreeFunction -> Logger ++ : getLogger <<private>>
Logger -> Logger ++ : activeLogger
Logger -> defaultLoggerInstance **
note over defaultLoggerInstance
  the default logger
  is configured via
  the alias in
  platform_settings.hpp
end note
return
return

logFreeFunction -> defaultLoggerInstance ++ : Logger::initLogger <<private>>
defaultLoggerInstance -> defaultLoggerInstance ++ : initiLoggerHook
return
return

return

@enduml
