if(UNIX AND NOT APPLE)
    if(CMAKE_SYSTEM_NAME MATCHES Linux)
        set(LINUX true)
    elseif(CMAKE_SYSTEM_NAME MATCHES QNX)
        set(QNX true)
    endif()
endif(UNIX AND NOT APPLE)

if(LINUX)
    set(ICEORYX_CXX_STANDARD 11)
elseif(QNX)
    set(ICEORYX_CXX_STANDARD 11)
elseif(WIN32)
    set(ICEORYX_CXX_STANDARD 11)
elseif(APPLE)
    set(ICEORYX_CXX_STANDARD 17)
endif(LINUX)

if ( WIN32 )
    set (ICEORYX_WARNINGS /W3 )
else()
    set (ICEORYX_WARNINGS -W -Wall -Wextra -Wuninitialized -Wpedantic -Wstrict-aliasing -Wcast-align -Wno-noexcept-type)
endif ( WIN32 )

if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    # temporary disable conversion warnings for clang
    # this needs to be fixed with iox-#163
    set(ICEORYX_WARNINGS ${ICEORYX_WARNINGS} -Wconversion)
endif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")

if(BUILD_STRICT)
    if ( WIN32 )
        set(ICEORYX_WARNINGS ${ICEORYX_WARNINGS} /WX)
    else()
        set(ICEORYX_WARNINGS ${ICEORYX_WARNINGS} -Werror)
    endif ( WIN32 )
endif(BUILD_STRICT)
