if(UNIX AND NOT APPLE)
    if(CMAKE_SYSTEM_NAME MATCHES Linux)
        set(LINUX true)
    elseif(CMAKE_SYSTEM_NAME MATCHES QNX)
        set(QNX true)
    endif()
endif(UNIX AND NOT APPLE)

if(LINUX)
    set(ICEORYX_CXX_STANDARD 11)
elseif(QNX)
    set(ICEORYX_CXX_STANDARD 11)
elseif(WIN32)
    set(ICEORYX_CXX_STANDARD 11)
elseif(APPLE)
    set(ICEORYX_CXX_STANDARD 17)
endif(LINUX)