# Copyright (c) 2020 by Apex.AI Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.

cmake_minimum_required(VERSION 3.5)

if(BUILD_DOC)

    set(DOXYGEN_GENERATE_HTML YES)
    set(DOXYGEN_GENERATE_LATEX YES)
    set(DOXYGEN_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/doc/${PROJECT_NAME})

    if(EXISTS "/usr/share/plantuml/plantuml.jar")
        set(DOXYGEN_PLANTUML_JAR_PATH /usr/share/plantuml/plantuml.jar)
    else()
        message(WARNING "plantuml.jar not found at '/usr/share/plantuml/', please set environment variable PLANTUML_JAR_PATH to the correct location.")
        set(PLANTUML_JAR_PATH "$ENV{PLANTUML_JAR_PATH}" CACHE STRING "PLANTUML location." )
    endif()

    set(DOXYGEN_ALIASES
    [["concurrent=\xrefitem concurrent \"Concurrent\" \"Concurrency\" " \
    "req=\xrefitem req \"Requirement\" \"Requirements\" " \
    "link=\xrefitem link \"Link\" \"Links\" " \
    swcomponent="@par Software Component:" \
    error="@par Error Handling:" \
    generatedcode="@par Generated by:"]]
    )

    doxygen_add_docs(
        doxygen_${PROJECT_NAME}
        ${PROJECT_SOURCE_DIR}/include
        ${PROJECT_SOURCE_DIR}/source
        ${PROJECT_SOURCE_DIR}/test
        ALL
    )

endif()
