// Copyright (c) 2019 by Robert Bosch GmbH. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

== Fixed string implementation
This document is intended to provide an overview of the fixed string implementation. The fixed string will be implemented in three steps. The first and second step are already completed and include:

.step 1:
* fixed but configurable size for fine grained control of the size of strings in different parts of the project (i.e. service names may be longer than process names) 
* the size will be set by a template parameter
		
In the second step, the functionality has been extended:

.step 2:
* enable assignment of smaller fixed size strings to larger ones (the other way around will be disabled by default (compile-time check with static_assert))
* copy constructor and assignment for different fixed sized strings
* comparison operators for different fixed size strings

.step 3:
* allow explicit enabling of assigning larger fixed size strings to smaller ones

