@startuml

[*] -down-> NOT_CONNECTED

NOT_CONNECTED -left-> NOT_CONNECTED : OFFER
NOT_CONNECTED -right-> CONNECT_REQUESTED : CONNECT

CONNECT_REQUESTED -left-> NOT_CONNECTED : DISCONNECT
CONNECT_REQUESTED -right-> CONNECT_REQUESTED : NACK
CONNECT_REQUESTED -down-> CONNECT_HANDSHAKE : OFFER

CONNECT_HANDSHAKE -left-> CONNECTED : ACK
CONNECT_HANDSHAKE -up-> CONNECT_REQUESTED : NACK

CONNECTED -up-> DISCONNECT_REQUESTED : DISCONNECT
CONNECTED -up-> CONNECT_REQUESTED : STOP_OFFER

DISCONNECT_REQUESTED -up--> NOT_CONNECTED : ACK/NACK

@enduml
