@startuml

class ServerPortData {
  chunkSenderData: ChunkSenderData
  chunkReceiverData: ChunkReceiverData
  offeringRequested: atomic<bool>
  offered: atomic<bool>
}


enum ServerRequestResult {
    TOO_MANY_REQUESTS_HELD_IN_PARALLEL,
    NO_PENDING_REQUESTS,
    UNDEFINED_CHUNK_RECEIVE_ERROR,
    NO_PENDING_REQUESTS_AND_SERVER_DOES_NOT_OFFER,
}

class ServerPortUser {
  offer(): void
  stopOffer(): void
  isOffered(): bool
  hasClients(): bool
  getRequest(): expected<const RequestHeader*, ServerRequestResult>
  releaseRequest(requestHeader: const RequestHeader*): void
  hasNewRequests(): void
  hasLostRequestsSinceLastCall(): bool
  allocateResponse(requestHeader: RequestHeader*, userPayloadSize: uint32_t, userPayloadAlignment: uint32_t): expected<ResponseHeader*, AllocationError>
  sendResponse(responseHeader: ResponseHeader*): void
  releaseResponse(responseHeader: const ResponseHeader*): void
  setConditionVariable(conditionVariable: ConditionVariableData&, notificationIndex: uint64_t): void
  unsetConditionVariable: void
  isConditionVariableSet(): bool
}

class ServerPortRouDi {
  tryGetCaProMessage(): optional<CaProMessage>
  dispatchCaProMessageAndGetPossibleResponse(caProMessage: const CaProMessage): optional<CaProMessage>
  releaseAllChunks(): void
}

ServerPortUser o-- ServerPortData
ServerPortData --o ServerPortRouDi

@enduml
