// Copyright (c) 2019 by Robert Bosch GmbH. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

== Fixed string implementation
This document is intended to provide an overview of the fixed string implementation. The fixed string will be implemented in three steps. The first and second step are already completed and include:

.step 1:
* fixed but configurable size for fine grained control of the size of strings in different parts of the project (i.e. service names may be longer than process names) 
* the size will be set by a template parameter
		
In the second step, the functionality has been extended:

.step 2:
* enable assignment of smaller fixed size strings to larger ones (the other way around will be disabled by default (compile-time check with static_assert))
* copy constructor and assignment for different fixed sized strings
* comparison operators for different fixed size strings

.step 3:
* allow explicit enabling of assigning larger fixed size strings to smaller ones

=== Interface:
----
	template <typename T1, typename T2>
	typename std::enable_if<(internal::IsCharArray<T1>::value || internal::IsCxxString<T1>::value)
	                            && (internal::IsCharArray<T2>::value || internal::IsCxxString<T2>::value),
	                        string<internal::GetCapa<T1>::capa + internal::GetCapa<T2>::capa>>::type
	concatenate(const T1& t1, const T2& t2);
	template <typename T1, typename T2, typename... Targs>
	typename std::enable_if<(internal::IsCharArray<T1>::value || internal::IsCxxString<T1>::value)
	                            && (internal::IsCharArray<T2>::value || internal::IsCxxString<T2>::value),
	                        string<internal::SumCapa<T1, T2, Targs...>::value>>::type
	concatenate(const T1& t1, const T2& t2, const Targs&... targs);

	template <typename T1, typename T2>
	typename std::enable_if<(internal::IsCharArray<T1>::value && internal::IsCxxString<T2>::value)
	                            || (internal::IsCxxString<T1>::value && internal::IsCharArray<T2>::value)
	                            || (internal::IsCxxString<T1>::value && internal::IsCxxString<T2>::value),
	                        string<internal::GetCapa<T1>::capa + internal::GetCapa<T2>::capa>>::type
	operator+(const T1& t1, const T2& t2);

	struct TruncateToCapacity_t
	{
	    explicit TruncateToCapacity_t() = default;
	};
	constexpr TruncateToCapacity_t TruncateToCapacity{};
	
	template <uint64_t Capacity>
	class string
	{
		static_assert(Capacity > 0, "The capacity of the fixed string must be greater than 0!");

	  public:
		constexpr string() noexcept = default;

		string(const string& other) noexcept;

		string(string&& other) noexcept;

		string& operator=(const string& rhs) noexcept;

		string& operator=(string&& rhs) noexcept;

		template <uint64_t N>
		string(const string<N>& other) noexcept;

		template <uint64_t N>
		string(string<N>&& other) noexcept;

		template <uint64_t N>
		string& operator=(const string<N>& str) noexcept;

		template <uint64_t N>
		string& operator=(string<N>&& rhs) noexcept;

		template <uint64_t N>
		string(const char (&other)[N]) noexcept;

		string(TruncateToCapacity_t, const char* const other) noexcept;
		string(TruncateToCapacity_t, const std::string& other) noexcept;
		string(TruncateToCapacity_t, const char* const other, const uint64_t count) noexcept;

		template <uint64_t N>
		string& operator=(const char (&rhs)[N]) noexcept;
	
	// step 1+2
		template <uint64_t N>
		string& assign(const string<N>& str) noexcept;
	// step 3
		enum class AssignmentPolicy {
			Assert,
			Truncate
		}
		template <uint64_t N, AssignmentPolicy P = AssignmentPolicy::Assert>
		string& assign(const string<N>& str) noexcept;
		
		template <uint64_t N>
		string& assign(const char (&str)[N]) noexcept;

		bool unsafe_assign(const char* const str) noexcept;
		bool unsafe_assign(const std::string& str) noexcept;
		
		template <uint64_t N>
		int64_t compare(const string<N>& other) const noexcept;
		template <uint64_t N>
		bool operator==(const string<N>& rhs) const noexcept;
		template <uint64_t N>
		bool operator!=(const string<N>& rhs) const noexcept;
		template <uint64_t N>
		bool operator<(const string<N>& rhs) const noexcept;
		template <uint64_t N>
		bool operator<=(const string<N>& rhs) const noexcept;
		template <uint64_t N>
		bool operator>(const string<N>& rhs) const noexcept;
		template <uint64_t N>
		bool operator>=(const string<N>& rhs) const noexcept;
		
		bool operator==(const char* const rhs) const noexcept;
		bool operator!=(const char* const rhs) const noexcept;
		
		const char* c_str() const noexcept;
		
		constexpr uint64_t size() const noexcept;

		constexpr uint64_t capacity() const noexcept;

		constexpr bool empty() const noexcept;
		
		operator std::string() const noexcept;

		template <typename T>
		string& operator+=(const T& t) noexcept;
		template <typename T>
		typename std::enable_if<internal::IsCharArray<T>::value || internal::IsCxxString<T>::value, string&>::type
		append(TruncateToCapacity_t, const T& t) noexcept;
		template <typename T>
		typename std::enable_if<internal::IsCharArray<T>::value || internal::IsCxxString<T>::value, bool>::type
		unsafe_append(const T& t) noexcept;

		iox::cxx::optional<string<Capacity>> substr(const uint64_t pos, const uint64_t count) const noexcept;
		iox::cxx::optional<string<Capacity>> substr(const uint64_t pos = 0) const noexcept;

		template <typename T>
		typename std::enable_if<std::is_same<T, std::string>::value || internal::IsCharArray<T>::value
		                            || internal::IsCxxString<T>::value,
		                        iox::cxx::optional<uint64_t>>::type
		find(const T& t, const uint64_t pos = 0) const noexcept;
		template <typename T>
		typename std::enable_if<std::is_same<T, std::string>::value || internal::IsCharArray<T>::value
		                            || internal::IsCxxString<T>::value,
		                        iox::cxx::optional<uint64_t>>::type
		find_first_of(const T& t, const uint64_t pos = 0) const noexcept;
		template <typename T>
		typename std::enable_if<std::is_same<T, std::string>::value || internal::IsCharArray<T>::value
		                            || internal::IsCxxString<T>::value,
		                        iox::cxx::optional<uint64_t>>::type
		find_last_of(const T& t, const uint64_t pos = Capacity) const noexcept;
	};

	template <uint64_t Capacity>
	inline bool operator==(const std::string& lhs, const string<Capacity>& rhs);
	template <uint64_t Capacity>
	inline bool operator==(const string<Capacity>& lhs, const std::string& rhs);
	template <uint64_t Capacity>
	inline bool operator!=(const std::string& lhs, const string<Capacity>& rhs);
	template <uint64_t Capacity>
	inline bool operator!=(const string<Capacity>& lhs, const std::string& rhs);
	template <uint64_t Capacity>
	inline bool operator==(const char* const lhs, const string<Capacity>& rhs);
	template <uint64_t Capacity>
	inline bool operator!=(const char* const lhs, const string<Capacity>& rhs);

	template <uint64_t Capacity>
	inline std::ostream& operator<<(std::ostream& stream, const string<Capacity>& str);
----	
