// Copyright (c) 2019 by Robert Bosch GmbH. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

== Fixed string implementation
This document is intended to provide an overview of the fixed string implementation. The fixed string will be implemented in two steps. The first step is already completed and includes:

.step 1:
* fixed but configurable size for fine grained control of the size of strings in different parts of the project (i.e. service names may be longer than process names) 
* the size will be set by a template parameter
		
In the second step, the functionality will be extended:

.step 2:
* enable assignment of smaller fixed size strings to larger ones (the other way around will be disabled by default (compile-time check with static_assert) but can be explicitly enabled)
* copy constructor and assignment for different fixed sized strings
* comparison operators for different fixed size strings

=== Interface:
----
	struct TruncateToCapacity_t
	{
	    explicit TruncateToCapacity_t() = default;
	};
	constexpr TruncateToCapacity_t TruncateToCapacity{};
	
	template <uint64_t Capacity>
	class string
	{
        static_assert(Capacity > 0, "The capacity of the fixed string must be greater than 0!");

	  public:
	    constexpr string() noexcept;
	
	// step 1
	    string(const string& other) noexcept;
	// step 2
	    template <uint64_t U>
	    string(const string<U>& other) noexcept;
	
	    string(string&& other) noexcept;
	
	// step 1
	    string& operator=(const string& rhs) noexcept;
	// step 2
	    template <uint64_t U>
	    string& operator=(const string<U>& str) noexcept;
	
	    string& operator=(string&& rhs) noexcept;

        template <int N>
	    string(const char (&other)[N]) noexcept;
	
	    string(TruncateToCapacity_t, const char* const other) noexcept;
	    string(TruncateToCapacity_t, const std::string& other) noexcept;
	    string(TruncateToCapacity_t, const char* const other, const uint64_t count) noexcept;
	
	    template <int N>
	    string& operator=(const char (&rhs)[N]) noexcept;
	
	// step 1
	    string& assign(const string& str) noexcept;
	// step 2
	    enum class AssignmentPolicy {
			Assert,
			Truncate
	    }
	    template <uint64_t U, AssignmentPolicy P = AssignmentPolicy::Assert>
	    string& assign(const string<U>& str) noexcept;
	
	    template <int N>
	    string& assign(const char (&str)[N]) noexcept;
	
	    bool unsafe_assign(const char* const str) noexcept;
	    bool unsafe_assign(const std::string& str) noexcept;
	
	// step 1
	    int compare(const string other) const noexcept;
	    bool operator==(const string& rhs) const noexcept;
	    bool operator!=(const string& rhs) const noexcept;
	    bool operator<(const string& rhs) const noexcept;
	    bool operator<=(const string& rhs) const noexcept;
	    bool operator>(const string& rhs) const noexcept;
	    bool operator>=(const string& rhs) const noexcept;
	// step 2 (templates with string<U>)

		bool operator==(const char* const rhs) const noexcept;
		bool operator!=(const char* const rhs) const noexcept;
	
	    const char* c_str() const noexcept;
	    constexpr uint64_t size() const noexcept;
	    constexpr uint64_t capacity() const noexcept;
	    operator std::string() const noexcept;
	};

	template <uint64_t Capacity>
	inline bool operator==(const std::string& lhs, const string<Capacity>& rhs);

	template <uint64_t Capacity>
	inline bool operator==(const string<Capacity>& lhs, const std::string& rhs);

	template <uint64_t Capacity>
	inline bool operator!=(const std::string& lhs, const string<Capacity>& rhs);

	template <uint64_t Capacity>
	inline bool operator!=(const string<Capacity>& lhs, const std::string& rhs);

	template <uint64_t Capacity>
	inline bool operator==(const char* const lhs, const string<Capacity>& rhs);

	template <uint64_t Capacity>
	inline bool operator!=(const char* const lhs, const string<Capacity>& rhs);

	template <uint64_t Capacity>
	inline std::ostream& operator<<(std::ostream& stream, const string<Capacity>& str);

----	
