@startuml

left to right direction

actor Iceoryx_Contributor

Iceoryx_Contributor --> (1. Create Diagram in PlantUML Editor)
Iceoryx_Contributor --> (2. Save it as new .puml file in iceoryx/doc/design/puml)
Iceoryx_Contributor --> (3. Export svg files via script in iceoryx/tools/ folder)
Iceoryx_Contributor --> (4. Create a Link in the Markdown file)
note left
The following snippet can be used to link against a svg file in markdown:
<code>
![your image description](puml/your_exported_vector_graphic.svg)
</code>
end note

@enduml
