@startuml
title Alternative B: Event-based notification between RouDi and PoshRuntime

participant RouDi
participant PoshRuntimeA
participant PoshRuntimeB

PoshRuntimeA->RouDi:  getMiddlewareInterface() / CREATE_INTERFACE
activate PoshRuntimeA
RouDi->PoshRuntimeA: CREATE_INTERFACE_ACK
deactivate PoshRuntimeA

RouDi->PoshRuntimeA: handleInterfaces() sends complete service registry
activate PoshRuntimeA

note right: Only react on CaproMessageSubType::SERVICE

PoshRuntimeB->RouDi: offer()
loop every 100ms
    RouDi->RouDi: doDiscovery()

    activate RouDi
    RouDi->RouDi: doDiscoveryForPublisherPorts()
    alt CaproMessage received
        RouDi->RouDi: sendToAllMatchingInterfaces()
        RouDi->PoshRuntimeA: dispatchCaProMessage()
    end
end
deactivate RouDi
PoshRuntimeA->PoshRuntimeA: wake up from wait()
deactivate PoshRuntimeA

@enduml
