@startuml

== Create a CommandLineOptionSet and define the application options ==

User -> CommandLineOptionSet ++ : CommandLineOptionSet(programName, onFailureCallback)
return CommandLineOptionSet

User -> CommandLineOptionSet ++ : addSwitch()

User -> CommandLineOptionSet ++ : addOptional()

User -> CommandLineOptionSet ++ : addRequired()

== Parse command line arguments ==

User -> CommandLineArgumentParser ++ : parse(CommandLineOptionSet)
return CommandLineValue

== Acquire command line option values ==

User -> CommandLineValue ++ : has(switchName)
return bool

User -> CommandLineValue ++ : get<TypeName>(optionalOptionName)
return TypeName

User -> CommandLineValue ++ : get<TypeName>(requiredOptionName)
return TypeName

User -> CommandLineValue ++ : binaryName()
return BinaryName_t

@enduml
