@startuml

== Create a CommandLineOptionSet and define the application options ==

User -> CommandLineOptionSet ++ : CommandLineOptionSet(programName, onFailureCallback)
return CommandLineOptionSet

User -> CommandLineOptionSet ++ : addSwitch()
return

User -> CommandLineOptionSet ++ : addOptional()
return

User -> CommandLineOptionSet ++ : addRequired()
return

== Parse command line arguments ==

User -> CommandLineArgumentParser ++ : parse(CommandLineOptionSet)
return CommandLineOptionValue

== Acquire command line option values ==

User -> CommandLineOptionValue ++ : has(switchName)
return bool

User -> CommandLineOptionValue ++ : get<TypeName>(optionalOptionName)
return TypeName

User -> CommandLineOptionValue ++ : get<TypeName>(requiredOptionName)
return TypeName

User -> CommandLineOptionValue ++ : binaryName()
return BinaryName_t

@enduml
