@startuml

class CommandLineOptionSet {
    +CommandLineOptionSet(programDescription, onFailureCallback)
    +addSwitch(..)
    +addOption(..)
    +addRequired(..)
}

class CommandLineOptionValue {
    +T get(optionName)
    +bool has(optionName)
    +BinaryName_t binaryName()
}

class CommandLineArgumentParser {
    +CommandLineOptionValue parse(CommandLineOptionSet, ..)
}

CommandLineOptionSet <|--- CommandLineArgumentParser
CommandLineOptionValue <|--- CommandLineArgumentParser

class OptionManager {
    +OptionManager(programDescription, onFailureCallback)
    +T defineOption(..)
    +populateDefinedOptions(..)
}

@enduml
